import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer"

// Register font (replace with actual font files if needed)
Font.register({
  family: "Roboto",
  fonts: [
    { src: "https://fonts.gstatic.com/s/roboto/v29/Roboto-Regular.ttf" },
    { src: "https://fonts.gstatic.com/s/roboto/v29/Roboto-Bold.ttf", fontWeight: "bold" },
  ],
})

// Styles for the PDF document
const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#fff",
    padding: 40,
    fontFamily: "Roboto",
  },
  section: {
    marginVertical: 10,
    marginHorizontal: 0,
  },
  title: {
    fontSize: 20,
    textAlign: "center",
    marginBottom: 20,
    fontWeight: "bold",
  },
  subtitle: {
    fontSize: 16,
    marginBottom: 10,
    fontWeight: "bold",
  },
  label: {
    fontSize: 12,
    marginBottom: 5,
  },
  value: {
    fontSize: 14,
    marginBottom: 10,
  },
  carInfoContainer: {
    marginBottom: 20,
  },
  carInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  carInfoLabel: {
    width: "40%",
    fontSize: 12,
  },
  carInfoValue: {
    width: "60%",
    fontSize: 12,
  },
  footer: {
    position: "absolute",
    fontSize: 12,
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: "center",
    color: "grey",
  },
})

const CarDetailsPDF = ({ carDetails, brandDetails, locale }) => {
  const isEnglish = locale === "en"

  const overviewData = [
    [
      {
        label: "Manufacturing Year",
        labelAr: "سنة الصنع",
        value: "2025",
      },
      {
        label: "Torque",
        labelAr: "عزم الدوران",
        value: "390 newton",
      },
      {
        label: "Power",
        labelAr: "القوة",
        value: "251 hp",
      },
    ],
    [
      {
        label: "Fuel Tank Capacity",
        labelAr: "سعة خزان الوقود",
        value: "60 liters",
      },
      {
        label: "Manufactured",
        labelAr: "الشركة المصنعة",
        value: "Jetour",
      },
      {
        label: "Power",
        labelAr: "القوة",
        value: "251 hp",
      },
    ],
    [
      {
        label: "Engine Type",
        labelAr: "نوع المحرك",
        value: "Benzene",
      },
      {
        label: "Transmission",
        labelAr: "ناقل الحركة",
        value: "Automatic",
      },
      {
        label: "Seating Capacity",
        labelAr: "سعة المقاعد",
        value: "5",
      },
    ],
    [
      {
        label: "Condition",
        labelAr: "الحالة",
        value: "New",
      },
      {
        label: "Fuel Consumption",
        labelAr: "استهلاك الوقود",
        value: "14.8 km/l",
      },
    ],
  ]

  return (
    <Document>
      <Page style={styles.page}>
        <Text style={styles.title}>
          {isEnglish
            ? `${brandDetails?.name || "Brand"} ${carDetails?.model?.name || "Model"} Details`
            : `تفاصيل ${brandDetails?.name || "الشركة"} ${carDetails?.model?.name || "الموديل"}`}
        </Text>

        <View style={styles.section}>
          <Text style={styles.subtitle}>{isEnglish ? "Car Information" : "معلومات السيارة"}</Text>
          <View style={styles.carInfoContainer}>
            {overviewData.map((row, rowIndex) => (
              <View key={rowIndex}>
                {row.map((item, index) => (
                  <View style={styles.carInfoRow} key={index}>
                    <Text style={styles.carInfoLabel}>{isEnglish ? item.label : item.labelAr}</Text>
                    <Text style={styles.carInfoValue}>{isEnglish ? item.value : item.valueAr || item.value}</Text>
                  </View>
                ))}
              </View>
            ))}
          </View>
        </View>

        <Text style={styles.footer}>{isEnglish ? "Generated by Our App" : "تم الإنشاء بواسطة تطبيقنا"}</Text>
      </Page>
    </Document>
  )
}

export default CarDetailsPDF

